### ISSUE TITLE
Many Crashes With 7-12 Players

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#247]
**Describe the bug**
Many Crashes With 7-12 Players

Exception code: 0xc0000409 (Stack Overflow)
Fault offset: 0x000000000006c9e8
Faulting process id: 0xba4
Faulting application start time: 0x01d736aea10df01c
Faulting application path: D:\GameServ\oregon-core.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll

There are NO dump file after crash!

**To Reproduce**
1.  Just Start Core and Play

**Eluna**
- [V] Enabled
- [ ] Disabled

**Crash**
There are NO dump file after crash!

**Additional context**

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/cb0b1e3b0eaa0c079a6ef77a348127284a1703fe

**Comment by talamortis** [comment]
Are you running in debug mode or release?

**Comment by talamortis** [comment]
Think this was an issue with players logging in while in shattrath city.

https://github.com/talamortis/OregonCore/commit/ad9bf61eb45a4905de88e69b3558e82b19d124fa

think i fixed in the above commit as it was an issue with grid loading

Will close issue please comment if still happens then will re-open

**Comment by PadreWoW** [comment]
This problem is not with shattrath 
I tested it with 2 players (1 in Ironforge and 1 in Teramore)
Both players just stood in one place - crashes after 10-40 min

**Comment by talamortis** [comment]
I think the issues was with CanSeeorDetect.

Test recent commit and let me know
