### ISSUE TITLE
Stuck in combat when fighting with Feralfen Hunter (with pet - Tamed Sporebat)

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#87]
![Безымянный](https://user-images.githubusercontent.com/6802530/69701188-6d047380-10fd-11ea-99f7-137f398dbd74.jpg)
**Describe the bug**
Stuck in combat when fighting with Feralfen Hunter (with pet - Tamed Sporebat)

**To Reproduce**
1.  Go to Zangarmarsh
2.  Start attack "Feralfen Hunter" or his pet (another small bug - you should not even damage it, just right click on Sporebat from far away and it starts to attack you)
3.  Try to escape
4.  Mob and his pet will return to his start position, but you stucks in combat until "Feralfen Hunter" dies

**Expected behavior**

**Screenshots**

**Additional context**
I think this bug with all mobs with pets......

**AC HASH/COMMIT:**

**Comment by PadreWoW** [comment]
I have a fix, but it's HACK fix and it's not repair "right-click aggro" bug, it only repairs "stuck in combat".


[Fix Stuck in Combat with Pets.txt](https://github.com/talamortis/OregonCore/files/4759020/Fix.Stuck.in.Combat.with.Pets.txt)

Please test it

**Comment by PadreWoW** [comment]
Any news?

**Comment by CTPEJIOK84** [comment]
With your fix it works better, but does not solve all problems with creature's pet.
1. If you attack a evading pet, you will hit it instead of a miss and combal will stuck. After that you can attack the pet without reaction from his side. Also out of combat, the pet’s health is not restored.
2. If you use any fear spell on the pet, the debuff will appear, but it will continue to attack.

1 - https://www.youtube.com/watch?v=tOuzo5d57XU
2 - https://www.youtube.com/watch?v=c_LVwiURQ9E

**Comment by PadreWoW** [comment]
Any news? This is really serious problem!
All npc pets are bugged!

**Comment by yuanf225** [comment]
> Any news? This is really serious problem!
> All npc pets are bugged!

You ask tele on discord

**Comment by talamortis** [comment]
Yes, this is an issue but trying to find where the issue is without applying a hackfix is like finding a needle in a haystack.
